steps:

  - id: "Instalação do App calculaRaizQuadradaGo"
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'app']
    env: ['GOPATH=.']
    
  - id: 'Executando o App calculaRaizQuadradaGo'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v','./...']
    env: ['GOPATH=.']

  - id: 'BUILD da Imagem'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/go-hpa, './']

  - id: 'PUSH da Imagem'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/go-hpa']